// Generated by scripts/generate_cocktails_ts.py — do not edit directly
// Source: Data/cocktails-100.csv

import negroniImg from "@/assets/negroni.jpg";
import old_fashionedImg from "@/assets/old-fashioned.jpg";
import margaritaImg from "@/assets/margarita.jpg";
import espresso_martiniImg from "@/assets/espresso-martini.jpg";
import daiquiriImg from "@/assets/daiquiri.jpg";
import manhattanImg from "@/assets/manhattan.jpg";
import whiskey_sourImg from "@/assets/whiskey-sour.jpg";
import mojitoImg from "@/assets/mojito.jpg";
import aperol_spritzImg from "@/assets/aperol-spritz.jpg";
import sazeracImg from "@/assets/sazerac.jpg";
import last_wordImg from "@/assets/last-word.jpg";
import palomaImg from "@/assets/paloma.jpg";
import pina_coladaImg from "@/assets/pina-colada.jpg";
import mai_taiImg from "@/assets/mai-tai.jpg";
import sidecarImg from "@/assets/sidecar.jpg";
import french_75Img from "@/assets/french-75.jpg";
import boulevardierImg from "@/assets/boulevardier.jpg";
import moscow_muleImg from "@/assets/moscow-mule.jpg";
import tom_collinsImg from "@/assets/tom-collins.jpg";
import aviationImg from "@/assets/aviation.jpg";
import paper_planeImg from "@/assets/paper-plane.jpg";
import penicillinImg from "@/assets/penicillin.jpg";
import gimletImg from "@/assets/gimlet.jpg";
import bees_kneesImg from "@/assets/bees-knees.jpg";
import caipirinhaImg from "@/assets/caipirinha.jpg";
import mint_julepImg from "@/assets/mint-julep.jpg";
import clover_clubImg from "@/assets/clover-club.jpg";
import brambleImg from "@/assets/bramble.jpg";
import vieux_carreImg from "@/assets/vieux-carre.jpg";
import trinidad_sourImg from "@/assets/trinidad-sour.jpg";
import cosmopolitanImg from "@/assets/cosmopolitan.jpg";
import hanky_pankyImg from "@/assets/hanky-panky.jpg";
import hemingway_daiquiriImg from "@/assets/hemingway-daiquiri.jpg";
import irish_coffeeImg from "@/assets/irish-coffee.jpg";
import pisco_sourImg from "@/assets/pisco-sour.jpg";
import rob_royImg from "@/assets/rob-roy.jpg";
import rusty_nailImg from "@/assets/rusty-nail.jpg";
import tequila_sunriseImg from "@/assets/tequila-sunrise.jpg";
import vesperImg from "@/assets/vesper.jpg";
import white_russianImg from "@/assets/white-russian.jpg";
import zombieImg from "@/assets/zombie.jpg";
import jungle_birdImg from "@/assets/jungle-bird.jpg";
import pornstar_martiniImg from "@/assets/pornstar-martini.jpg";

import type { Cocktail } from "@/types/cocktail";

export const cocktails: Cocktail[] = [
  {
    id: "negroni",
    name: "Negroni",
    image: negroniImg,
    tier: 0,
    standardRecipe: {
      id: "negroni-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "3 cl" },
          { name: "Italian red bitter liqueur", amount: "3 cl" },
          { name: "Martini Rosso sweet vermouth", amount: "3 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "old-fashioned",
    name: "Old Fashioned",
    image: old_fashionedImg,
    tier: 0,
    standardRecipe: {
      id: "old-fashioned-std",
      label: "Standard",
      ingredients: [
          { name: "Bourbon whiskey", amount: "6 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.25 cl" },
          { name: "Angostura Aromatic Bitters", amount: "3 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "margarita",
    name: "Margarita",
    image: margaritaImg,
    tier: 0,
    standardRecipe: {
      id: "margarita-std",
      label: "Standard",
      ingredients: [
          { name: "Patrón Silver blanco tequila", amount: "4.5 cl" },
          { name: "De Kuyper Triple Sec (40%)", amount: "2.25 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Luxardo cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "espresso-martini",
    name: "Espresso Martini",
    image: espresso_martiniImg,
    tier: 0,
    standardRecipe: {
      id: "espresso-martini-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "4.5 cl" },
          { name: "Espresso coffee (freshly made & hot)", amount: "3 cl" },
          { name: "Coffee liqueur", amount: "2 cl" },
          { name: "Difford\'s Saline Solution (or ½ pinch salt) (optional)", amount: "2 drop" }
      ],
      method: "Shake all ingredients vigorously with ice. Fine strain into glass.",
      glass: "Martini glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "daiquiri",
    name: "Daiquiri",
    image: daiquiriImg,
    tier: 1,
    standardRecipe: {
      id: "daiquiri-std",
      label: "Standard",
      ingredients: [
          { name: "Bacardi Carta Blanca light rum", amount: "5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1 cl" },
          { name: "Difford\'s Daiquiri Bitters (optional)", amount: "4 drop" },
          { name: "Chilled water (omit if using wet ice)", amount: "1 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "dry-martini",
    name: "Dry Martini",
    image: "",
    tier: 1,
    standardRecipe: {
      id: "dry-martini-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "6.25 cl" },
          { name: "Martini Extra Dry vermouth", amount: "1.25 cl" },
          { name: "Orange Bitters by Angostura (optional)", amount: "1 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Martini glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "manhattan",
    name: "Manhattan",
    image: manhattanImg,
    tier: 1,
    standardRecipe: {
      id: "manhattan-std",
      label: "Standard",
      ingredients: [
          { name: "Bourbon whiskey", amount: "6 cl" },
          { name: "Martini Extra Dry vermouth", amount: "2.5 cl" },
          { name: "Angostura Aromatic Bitters", amount: "2 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "whiskey-sour",
    name: "Whiskey Sour",
    image: whiskey_sourImg,
    tier: 1,
    standardRecipe: {
      id: "whiskey-sour-std",
      label: "Standard",
      ingredients: [
          { name: "Bulleit Kentucky Straight Bourbon Whiskey (45%)", amount: "4 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1 cl" },
          { name: "Egg white", amount: "1.5 cl" }
      ],
      method: "Dry shake all ingredients without ice. Shake again with ice. Strain into chilled glass.",
      glass: "Old-fashioned glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "mojito",
    name: "Mojito",
    image: mojitoImg,
    tier: 1,
    standardRecipe: {
      id: "mojito-std",
      label: "Standard",
      ingredients: [
          { name: "Mint leaves", amount: "14 fresh" },
          { name: "Havana Club 3 Year Old rum", amount: "6 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1 cl" },
          { name: "Thomas Henry Soda Water", amount: "1.5 cl" }
      ],
      method: "Muddle herbs/sugar in shaker. Add remaining ingredients. Shake with ice. Strain. Top with soda.",
      glass: "Collins glass",
      garnish: "Mint sprig",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "aperol-spritz",
    name: "Aperol Spritz",
    image: aperol_spritzImg,
    tier: 1,
    standardRecipe: {
      id: "aperol-spritz-std",
      label: "Standard",
      ingredients: [
          { name: "Prosecco sparkling wine", amount: "9 cl" },
          { name: "Bittersweet orange-red aperitivo", amount: "6 cl" },
          { name: "Thomas Henry Soda Water", amount: "3 cl" }
      ],
      method: "Shake base ingredients with ice. Strain into glass. Top with soda.",
      glass: "Wine glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "sazerac",
    name: "Sazerac",
    image: sazeracImg,
    tier: 2,
    standardRecipe: {
      id: "sazerac-std",
      label: "Standard",
      ingredients: [
          { name: "La Fée Parisienne absinthe", amount: "1 cl" },
          { name: "Chilled water", amount: "7 cl" },
          { name: "Rémy Martin 1738 Cognac", amount: "2 cl" },
          { name: "Straight rye whiskey (100 proof / 50% alc./vol.)", amount: "2 cl" },
          { name: "Bourbon whiskey", amount: "2 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1 cl" },
          { name: "Peychaud\'s or other Creole-style bitters", amount: "3 dash" },
          { name: "Angostura Aromatic Bitters", amount: "1 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "last-word",
    name: "Last Word",
    image: last_wordImg,
    tier: 2,
    standardRecipe: {
      id: "last-word-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "3 cl" },
          { name: "Green Chartreuse liqueur", amount: "2 cl" },
          { name: "Luxardo Maraschino liqueur", amount: "2 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2 cl" },
          { name: "Chilled water (omit if using wet ice)", amount: "1 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "paloma",
    name: "Paloma",
    image: palomaImg,
    tier: 2,
    standardRecipe: {
      id: "paloma-std",
      label: "Standard",
      ingredients: [
          { name: "Patrón Silver blanco tequila", amount: "5 cl" },
          { name: "Grapefruit juice (pink)", amount: "2.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.25 cl" },
          { name: "Agave syrup", amount: "0.75 cl" },
          { name: "Thomas Henry Pink Grapefruit soda", amount: "5 cl" }
      ],
      method: "Muddle herbs/sugar in shaker. Add remaining ingredients. Shake with ice. Strain. Top with soda.",
      glass: "Collins glass",
      garnish: "Salt rim",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "pina-colada",
    name: "Pina Colada",
    image: pina_coladaImg,
    tier: 2,
    standardRecipe: {
      id: "pina-colada-std",
      label: "Standard",
      ingredients: [
          { name: "Bacardi Carta Blanca light rum", amount: "6 cl" },
          { name: "Pineapple juice (fresh pressed)", amount: "9 cl" },
          { name: "Cream of coconut (e.g. Coco Lopez, Re\'al etc.)", amount: "2 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" }
      ],
      method: "Blend all ingredients with crushed ice until smooth. Pour into glass.",
      glass: "Pineapple shell (frozen) glass",
      garnish: "Luxardo cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "mai-tai",
    name: "Mai Tai",
    image: mai_taiImg,
    tier: 2,
    standardRecipe: {
      id: "mai-tai-std",
      label: "Standard",
      ingredients: [
          { name: "Havana Club 7yo rum", amount: "6 cl" },
          { name: "Orange Curaçao liqueur", amount: "1.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Giffard Orgeat Syrup", amount: "1 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "0.75 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Double old-fashioned",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "sidecar",
    name: "Sidecar",
    image: sidecarImg,
    tier: 2,
    standardRecipe: {
      id: "sidecar-std",
      label: "Standard",
      ingredients: [
          { name: "Rémy Martin 1738 Cognac", amount: "4.5 cl" },
          { name: "De Kuyper Triple Sec (40%)", amount: "3 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Chilled water (omit if using wet ice)", amount: "1.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "french-75",
    name: "French 75",
    image: french_75Img,
    tier: 2,
    standardRecipe: {
      id: "french-75-std",
      label: "Standard",
      ingredients: [
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Powdered sugar (ground in mortar and pestle) (or use 5ml of 2:1 sugar syrup per spoon)", amount: "1 1⁄2 spoon" },
          { name: "Rutte Dry Gin", amount: "4.5 cl" },
          { name: "Brut Champagne", amount: "7.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into glass.",
      glass: "Flute glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "boulevardier",
    name: "Boulevardier",
    image: boulevardierImg,
    tier: 2,
    standardRecipe: {
      id: "boulevardier-std",
      label: "Standard",
      ingredients: [
          { name: "Bourbon whiskey", amount: "4.5 cl" },
          { name: "Martini Rosso sweet vermouth", amount: "3 cl" },
          { name: "Italian red bitter liqueur", amount: "3 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "bloody-mary",
    name: "Bloody Mary",
    image: "",
    tier: 2,
    standardRecipe: {
      id: "bloody-mary-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "6 cl" },
          { name: "Tomato juice", amount: "12 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Hot pepper sauce (red)", amount: "8 drop" },
          { name: "Worcestershire sauce", amount: "4 dash" },
          { name: "Black pepper", amount: "2 grind" },
          { name: "Celery salt", amount: "1 pinch" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Salt rim",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "moscow-mule",
    name: "Moscow Mule",
    image: moscow_muleImg,
    tier: 2,
    standardRecipe: {
      id: "moscow-mule-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "6 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1 cl" },
          { name: "Thomas Henry Ginger Beer", amount: "9 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Copper mug or Collins glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "tom-collins",
    name: "Tom Collins",
    image: tom_collinsImg,
    tier: 2,
    standardRecipe: {
      id: "tom-collins-std",
      label: "Standard",
      ingredients: [
          { name: "Portobello Old Tom gin", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" },
          { name: "Thomas Henry Soda Water", amount: "5 cl" }
      ],
      method: "Shake base ingredients with ice. Strain into glass. Top with soda.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "aviation",
    name: "Aviation",
    image: aviationImg,
    tier: 2,
    standardRecipe: {
      id: "aviation-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "5.25 cl" },
          { name: "Luxardo Maraschino liqueur", amount: "1.5 cl" },
          { name: "Crème de violette liqueur", amount: "0.75 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Chilled water (omit if using wet ice)", amount: "0.75 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "paper-plane",
    name: "Paper Plane",
    image: paper_planeImg,
    tier: 2,
    standardRecipe: {
      id: "paper-plane-std",
      label: "Standard",
      ingredients: [
          { name: "Bourbon whiskey", amount: "2.25 cl" },
          { name: "Amaro Nonino Quintessentia", amount: "2.25 cl" },
          { name: "Bittersweet orange-red aperitivo", amount: "2.25 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.25 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "penicillin",
    name: "Penicillin",
    image: penicillinImg,
    tier: 2,
    standardRecipe: {
      id: "penicillin-std",
      label: "Standard",
      ingredients: [
          { name: "Dewar\'s 12 Year Old Scotch whisky", amount: "4.5 cl" },
          { name: "Ginger liqueur", amount: "1.5 cl" },
          { name: "Islay single malt (peated) Scotch whisky", amount: "1 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2 cl" },
          { name: "Honey syrup (3 honey to 1 water)", amount: "2 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Old-fashioned glass",
      garnish: "Candied ginger",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "gimlet",
    name: "Gimlet",
    image: gimletImg,
    tier: 2,
    standardRecipe: {
      id: "gimlet-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "5 cl" },
          { name: "Lime cordial (sweetened lime juice)", amount: "2 cl" },
          { name: "Rutte Old Simon Genever", amount: "1 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "0.5 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "0.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "0.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "bees-knees",
    name: "Bee's Knees",
    image: bees_kneesImg,
    tier: 2,
    standardRecipe: {
      id: "bees-knees-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Honey syrup (3 honey to 1 water)", amount: "1.5 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "1 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "caipirinha",
    name: "Caipirinha",
    image: caipirinhaImg,
    tier: 2,
    standardRecipe: {
      id: "caipirinha-std",
      label: "Standard",
      ingredients: [
          { name: "Lime (fresh) (chopped)", amount: "1⁄2 fresh" },
          { name: "Powdered sugar (ground in mortar and pestle)", amount: "3 spoon" },
          { name: "Chilled water (omit if using wet ice)", amount: "2.25 cl" },
          { name: "Novo Fogo Silver cachaça (from freezer)", amount: "6 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Highball (max 10oz/300ml)",
      garnish: "Sugar rim",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "mint-julep",
    name: "Mint Julep",
    image: mint_julepImg,
    tier: 2,
    standardRecipe: {
      id: "mint-julep-std",
      label: "Standard",
      ingredients: [
          { name: "Mint leaves", amount: "12 fresh" },
          { name: "Bourbon whiskey", amount: "7 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "2 cl" },
          { name: "Angostura Aromatic Bitters", amount: "2 dash" }
      ],
      method: "Muddle mint and sugar gently in shaker. Add remaining ingredients. Shake with ice. Fine strain into glass.",
      glass: "Julep tin",
      garnish: "Mint sprig",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "clover-club",
    name: "Clover Club",
    image: clover_clubImg,
    tier: 2,
    standardRecipe: {
      id: "clover-club-std",
      label: "Standard",
      ingredients: [
          { name: "Gin", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Raspberry (framboise) sugar syrup", amount: "1.5 cl" },
          { name: "Pasteurised egg white", amount: "1.5 cl" },
          { name: "Raspberries (fresh)", amount: "3 whole" }
      ],
      method: "Dry shake all ingredients without ice. Shake again with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "bramble",
    name: "Bramble",
    image: brambleImg,
    tier: 2,
    standardRecipe: {
      id: "bramble-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "4.5 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "3 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.25 cl" },
          { name: "Giffard Crème de Mûre liqueur", amount: "1.25 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Double old-fashioned",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "corpse-reviver-2",
    name: "Corpse Reviver #2",
    image: "",
    tier: 2,
    standardRecipe: {
      id: "corpse-reviver-2-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "2.25 cl" },
          { name: "De Kuyper Triple Sec (40%)", amount: "2.25 cl" },
          { name: "Lillet Blanc (or other aromatized wine)", amount: "2.25 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup) (optional)", amount: "0.25 cl" },
          { name: "La Fée Parisienne absinthe", amount: "2 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "vieux-carre",
    name: "Vieux Carré",
    image: vieux_carreImg,
    tier: 2,
    standardRecipe: {
      id: "vieux-carre-std",
      label: "Standard",
      ingredients: [
          { name: "Bourbon whiskey", amount: "2.25 cl" },
          { name: "Rémy Martin 1738 Cognac", amount: "2.25 cl" },
          { name: "Martini Rosso sweet vermouth", amount: "2.25 cl" },
          { name: "Bénédictine D.O.M.", amount: "1 cl" },
          { name: "Peychaud\'s or other Creole-style bitters", amount: "2 dash" },
          { name: "Angostura Aromatic Bitters", amount: "1 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "suffering-bastard",
    name: "Suffering Bastard",
    image: "",
    tier: 2,
    standardRecipe: {
      id: "suffering-bastard-std",
      label: "Standard",
      ingredients: [
          { name: "Rémy Martin 1738 Cognac", amount: "3 cl" },
          { name: "Rutte Dry Gin", amount: "3 cl" },
          { name: "Lime cordial (sweetened lime juice)", amount: "2 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1 cl" },
          { name: "Angostura Aromatic Bitters", amount: "3 dash" },
          { name: "Thomas Henry Ginger Beer", amount: "10 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Tiki mug or collins",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "trinidad-sour",
    name: "Trinidad Sour",
    image: trinidad_sourImg,
    tier: 2,
    standardRecipe: {
      id: "trinidad-sour-std",
      label: "Standard",
      ingredients: [
          { name: "Angostura Aromatic Bitters", amount: "4.5 cl" },
          { name: "Straight rye whiskey (100 proof / 50% alc./vol.)", amount: "1.5 cl" },
          { name: "Giffard Orgeat Syrup", amount: "3 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.25 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "americano",
    name: "Americano",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "americano-std",
      label: "Standard",
      ingredients: [
          { name: "Italian red bitter liqueur", amount: "4.5 cl" },
          { name: "Martini Rosso sweet vermouth", amount: "4.5 cl" },
          { name: "Thomas Henry Soda Water", amount: "7.5 cl" }
      ],
      method: "Shake base ingredients with ice. Strain into glass. Top with soda.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "bellini",
    name: "Bellini",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "bellini-std",
      label: "Standard",
      ingredients: [
          { name: "Peach purée", amount: "6 cl" },
          { name: "Peachtree peach schnapps", amount: "1 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "0.75 cl" },
          { name: "Prosecco sparkling wine", amount: "6 cl" }
      ],
      method: "Shake base ingredients with ice. Strain into glass. Top with soda.",
      glass: "Flute glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "black-russian",
    name: "Black Russian",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "black-russian-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "6 cl" },
          { name: "Coffee liqueur", amount: "2.25 cl" }
      ],
      method: "Shake all ingredients vigorously with ice. Fine strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "blood-and-sand",
    name: "Blood & Sand",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "blood-and-sand-std",
      label: "Standard",
      ingredients: [
          { name: "Orange juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Antica Formula or other well aged sweet vermouth", amount: "2.25 cl" },
          { name: "Dewar\'s 12 Year Old \'The Ancestor\' blended Scotch whisky", amount: "3.5 cl" },
          { name: "Giffard Cherry Brandy Liqueur", amount: "2.25 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "casino",
    name: "Casino",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "casino-std",
      label: "Standard",
      ingredients: [
          { name: "Portobello Old Tom gin", amount: "4.5 cl" },
          { name: "Luxardo Maraschino liqueur", amount: "2.25 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Orange Bitters by Angostura", amount: "1 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Nick & Nora glass",
      garnish: "Luxardo cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "champagne-cocktail",
    name: "Champagne Cocktail",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "champagne-cocktail-std",
      label: "Standard",
      ingredients: [
          { name: "Sugar cube", amount: "1 cube" },
          { name: "Angostura Aromatic Bitters", amount: "3 dash" },
          { name: "Rémy Martin 1738 Cognac", amount: "3 cl" },
          { name: "Brut Champagne", amount: "10 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into glass.",
      glass: "Flute glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "cosmopolitan",
    name: "Cosmopolitan",
    image: cosmopolitanImg,
    tier: 3,
    standardRecipe: {
      id: "cosmopolitan-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "3 cl" },
          { name: "De Kuyper Triple Sec (40%)", amount: "3 cl" },
          { name: "Cranberry juice (sweetened)", amount: "4.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Orange Bitters by Angostura", amount: "1 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "cuba-libre",
    name: "Cuba Libre",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "cuba-libre-std",
      label: "Standard",
      ingredients: [
          { name: "Havana Club 3 Year Old rum", amount: "5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "0.5 cl" },
          { name: "Angostura Aromatic Bitters", amount: "1 dash" },
          { name: "Cola (e.g. Coca Cola & Pepsi Cola)", amount: "12 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "derby",
    name: "Derby",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "derby-std",
      label: "Standard",
      ingredients: [
          { name: "Havana Club 3 Year Old rum", amount: "4.5 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "3 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "dirty-martini",
    name: "Dirty Martini",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "dirty-martini-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "6.25 cl" },
          { name: "Martini Extra Dry vermouth", amount: "1.5 cl" },
          { name: "Olive bitters", amount: "5 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Martini glass",
      garnish: "Olive",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "el-diablo",
    name: "El Diablo",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "el-diablo-std",
      label: "Standard",
      ingredients: [
          { name: "Patrón Reposado tequila", amount: "4.5 cl" },
          { name: "Giffard Noir de Bourgogne Cassis", amount: "1.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Thomas Henry Ginger Beer", amount: "6 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "godfather",
    name: "Godfather",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "godfather-std",
      label: "Standard",
      ingredients: [
          { name: "Dewar\'s 12 Year Old Scotch whisky", amount: "6 cl" },
          { name: "Disaronno amaretto", amount: "2 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Old-fashioned glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "golden-dream",
    name: "Golden Dream",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "golden-dream-std",
      label: "Standard",
      ingredients: [
          { name: "De Kuyper Triple Sec (40%)", amount: "2.5 cl" },
          { name: "Galliano L\'Autentico liqueur", amount: "2.5 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "3.75 cl" },
          { name: "Single cream / half-and-half", amount: "2.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "grasshopper",
    name: "Grasshopper",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "grasshopper-std",
      label: "Standard",
      ingredients: [
          { name: "Giffard Peppermint Pastille crème de menthe", amount: "3 cl" },
          { name: "Dutch Cacao white crème de cacao", amount: "3 cl" },
          { name: "Single cream / half-and-half", amount: "3 cl" }
      ],
      method: "Muddle mint and sugar gently in shaker. Add remaining ingredients. Shake with ice. Fine strain into glass.",
      glass: "Coupe glass",
      garnish: "Mint sprig",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "hanky-panky",
    name: "Hanky Panky",
    image: hanky_pankyImg,
    tier: 3,
    standardRecipe: {
      id: "hanky-panky-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "4.5 cl" },
          { name: "Martini Rosso sweet vermouth", amount: "4.5 cl" },
          { name: "Fernet liqueur", amount: "0.25 cl" },
          { name: "Orange juice (freshly squeezed) (optional)", amount: "0.125 cl" },
          { name: "Difford\'s Saline Solution (or ½ pinch salt) (optional)", amount: "2 drop" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Nick & Nora glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "harvey-wallbanger",
    name: "Harvey Wallbanger",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "harvey-wallbanger-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "4.5 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "6.75 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "0.5 cl" },
          { name: "Orange Bitters by Angostura", amount: "2 dash" },
          { name: "Galliano L\'Autentico liqueur", amount: "1.25 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "hemingway-daiquiri",
    name: "Hemingway Daiquiri",
    image: hemingway_daiquiriImg,
    tier: 3,
    standardRecipe: {
      id: "hemingway-daiquiri-std",
      label: "Standard",
      ingredients: [
          { name: "La Fée Parisienne absinthe", amount: "0.75 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.25 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.25 cl" },
          { name: "Brut Champagne", amount: "12 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Flute glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "horses-neck",
    name: "Horse's Neck",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "horses-neck-std",
      label: "Standard",
      ingredients: [
          { name: "Bourbon whiskey", amount: "4.5 cl" },
          { name: "Angostura Aromatic Bitters", amount: "2 dash" },
          { name: "Thomas Henry Ginger Ale", amount: "Top up with" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Highball (max 10oz/300ml)",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "irish-coffee",
    name: "Irish Coffee",
    image: irish_coffeeImg,
    tier: 3,
    standardRecipe: {
      id: "irish-coffee-std",
      label: "Standard",
      ingredients: [
          { name: "Irish whiskey", amount: "3 cl" },
          { name: "Demerara / dark Muscovado sugar syrup (2 sugar to 1 water)", amount: "1 cl" },
          { name: "Filter coffee (hot)", amount: "6 cl" },
          { name: "Double cream / heavy cream", amount: "3 cl" }
      ],
      method: "Shake all ingredients vigorously with ice. Fine strain into glass.",
      glass: "Toddy glass",
      garnish: "Three coffee beans",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "john-collins",
    name: "John Collins",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "john-collins-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" },
          { name: "Thomas Henry Soda Water", amount: "5 cl" }
      ],
      method: "Shake base ingredients with ice. Strain into glass. Top with soda.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "kir-royale",
    name: "Kir Royale",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "kir-royale-std",
      label: "Standard",
      ingredients: [
          { name: "Giffard Noir de Bourgogne Cassis", amount: "1.5 cl" },
          { name: "Brut Champagne", amount: "12 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into glass.",
      glass: "Flute glass",
      garnish: "None",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "lemon-drop",
    name: "Lemon Drop",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "lemon-drop-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "1.5 cl" },
          { name: "De Kuyper Triple Sec (40%)", amount: "1.5 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into glass.",
      glass: "Shot glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "long-island-iced-tea",
    name: "Long Island Iced Tea",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "long-island-iced-tea-std",
      label: "Standard",
      ingredients: [
          { name: "Bacardi Carta Blanca light rum", amount: "1.25 cl" },
          { name: "Rutte Dry Gin", amount: "1.25 cl" },
          { name: "Ketel One Vodka", amount: "1.25 cl" },
          { name: "Patrón Silver blanco tequila", amount: "1.25 cl" },
          { name: "De Kuyper Triple Sec (40%)", amount: "1.25 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.25 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.25 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.25 cl" },
          { name: "Cola (e.g. Coca Cola & Pepsi Cola)", amount: "6 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "martinez",
    name: "Martinez",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "martinez-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Old Simon Genever", amount: "6 cl" },
          { name: "Martini Rosso sweet vermouth", amount: "3 cl" },
          { name: "Martini Extra Dry vermouth", amount: "0.75 cl" },
          { name: "Orange Curaçao liqueur", amount: "0.75 cl" },
          { name: "Angostura Aromatic Bitters", amount: "1 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "mary-pickford",
    name: "Mary Pickford",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "mary-pickford-std",
      label: "Standard",
      ingredients: [
          { name: "Havana Club 3 Year Old rum", amount: "6 cl" },
          { name: "Pineapple juice (fresh pressed)", amount: "4.5 cl" },
          { name: "Luxardo Maraschino liqueur", amount: "0.5 cl" },
          { name: "Giffard Grenadine syrup", amount: "0.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Luxardo cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "monkey-gland",
    name: "Monkey Gland",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "monkey-gland-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "6 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "2 cl" },
          { name: "Giffard Grenadine syrup", amount: "0.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "0.25 cl" },
          { name: "La Fée Parisienne absinthe (omit for Cocktails Made Easy)", amount: "3 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "morning-glory-fizz",
    name: "Morning Glory Fizz",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "morning-glory-fizz-std",
      label: "Standard",
      ingredients: [
          { name: "Speyside single malt Scotch whisky (from freezer)", amount: "6 cl" },
          { name: "La Fée Parisienne absinthe", amount: "0.25 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" },
          { name: "Pasteurised egg white", amount: "2 cl" },
          { name: "Thomas Henry Soda Water", amount: "Top up with" }
      ],
      method: "Dry shake all ingredients without ice. Shake again with ice. Strain into glass. Top with soda.",
      glass: "Highball (max 10oz/300ml)",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "mulled-wine",
    name: "Mulled Wine",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "mulled-wine-std",
      label: "Standard",
      ingredients: [
          { name: "Clove", amount: "5 dried" },
          { name: "Freshly grated nutmeg", amount: "1 pinch" },
          { name: "Cinnamon powder", amount: "1 pinch" },
          { name: "Tawny port", amount: "4.5 cl" },
          { name: "Shiraz red wine", amount: "4.5 cl" },
          { name: "Orange (fresh fruit)", amount: "1 wedge" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Honey", amount: "2 spoon" },
          { name: "Grand Marnier or other cognac orange liqueur", amount: "1.5 cl" },
          { name: "Boiling water", amount: "Top up with" }
      ],
      method: "Build in warmed glass. Add ingredients in order. Float cream on top.",
      glass: "Toddy glass",
      garnish: "Cinnamon stick",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "new-york-sour",
    name: "New York Sour",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "new-york-sour-std",
      label: "Standard",
      ingredients: [
          { name: "Bourbon whiskey", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "3 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" },
          { name: "Angostura Aromatic Bitters", amount: "1 dash" },
          { name: "Pasteurised egg white (optional)", amount: "1.5 cl" },
          { name: "Claret red wine", amount: "1.5 cl" }
      ],
      method: "Dry shake all ingredients without ice. Shake again with ice. Strain into chilled glass.",
      glass: "Old-fashioned glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "old-cuban",
    name: "Old Cuban",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "old-cuban-std",
      label: "Standard",
      ingredients: [
          { name: "Mint leaves", amount: "6 fresh" },
          { name: "Havana Club 7yo rum", amount: "4.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" },
          { name: "Angostura Aromatic Bitters", amount: "2 dash" },
          { name: "Brut Champagne", amount: "2.25 cl" }
      ],
      method: "Muddle mint and sugar gently in shaker. Add remaining ingredients. Shake with ice. Fine strain into glass.",
      glass: "Coupe glass",
      garnish: "Mint sprig",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "paradise",
    name: "Paradise",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "paradise-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "4.5 cl" },
          { name: "De Kuyper Apricot Brandy liqueur", amount: "2.25 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Orange Bitters by Angostura", amount: "2 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "pisco-sour",
    name: "Pisco Sour",
    image: pisco_sourImg,
    tier: 3,
    standardRecipe: {
      id: "pisco-sour-std",
      label: "Standard",
      ingredients: [
          { name: "Lime juice (freshly squeezed)", amount: "3 cl" },
          { name: "Powdered sugar (ground in mortar and pestle)", amount: "6 spoon" },
          { name: "BarSol Mosto Verde Italia Pisco", amount: "6 cl" },
          { name: "Pasteurised egg white", amount: "1.5 cl" }
      ],
      method: "Dry shake all ingredients without ice. Shake again with ice. Strain into chilled glass.",
      glass: "Goblet glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "planters-punch",
    name: "Planter's Punch",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "planters-punch-std",
      label: "Standard",
      ingredients: [
          { name: "Overproof pot still rum", amount: "4.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "3 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" },
          { name: "Chilled water", amount: "6 cl" },
          { name: "Angostura Aromatic Bitters", amount: "3 dash" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "ramos-gin-fizz",
    name: "Ramos Gin Fizz",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "ramos-gin-fizz-std",
      label: "Standard",
      ingredients: [
          { name: "Portobello Old Tom gin", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "2.25 cl" },
          { name: "Orange flower/blossom water", amount: "0.125 cl" },
          { name: "Vanilla extract (optional)", amount: "3 drop" },
          { name: "Pasteurised egg white", amount: "2.25 cl" },
          { name: "Single cream / half-and-half", amount: "2.25 cl" },
          { name: "Thomas Henry Soda Water", amount: "Top up with" }
      ],
      method: "Dry shake all ingredients without ice. Shake again with ice. Strain into glass. Top with soda.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "rob-roy",
    name: "Rob Roy",
    image: rob_royImg,
    tier: 3,
    standardRecipe: {
      id: "rob-roy-std",
      label: "Standard",
      ingredients: [
          { name: "Dewar\'s 12 Year Old Scotch whisky", amount: "5 cl" },
          { name: "Martini Rosso sweet vermouth", amount: "3 cl" },
          { name: "Bob\'s Abbotts bitters", amount: "2 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "rose-cocktail",
    name: "Rose",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "rose-cocktail-std",
      label: "Standard",
      ingredients: [
          { name: "Noilly Prat Extra Dry Vermouth", amount: "6 cl" },
          { name: "Kirschwasser (cherry) eau-de-vie", amount: "3 cl" },
          { name: "Raspberry (framboise) sugar syrup", amount: "1⁄2 spoon" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Luxardo cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "rusty-nail",
    name: "Rusty Nail",
    image: rusty_nailImg,
    tier: 3,
    standardRecipe: {
      id: "rusty-nail-std",
      label: "Standard",
      ingredients: [
          { name: "Dewar\'s 12 Year Old Scotch whisky", amount: "4.5 cl" },
          { name: "Drambuie liqueur", amount: "1.5 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "scorpion",
    name: "Scorpion",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "scorpion-std",
      label: "Standard",
      ingredients: [
          { name: "Havana Club 3 Year Old rum", amount: "4.5 cl" },
          { name: "Rémy Martin 1738 Cognac", amount: "2.25 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "3 cl" },
          { name: "Giffard Orgeat Syrup", amount: "1.5 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "sex-on-the-beach",
    name: "Sex on the Beach",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "sex-on-the-beach-std",
      label: "Standard",
      ingredients: [
          { name: "Peachtree peach schnapps", amount: "2 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "3 cl" },
          { name: "Pineapple juice (fresh pressed)", amount: "3 cl" },
          { name: "Ketel One Vodka", amount: "4.5 cl" },
          { name: "Cranberry juice (sweetened)", amount: "3 cl" },
          { name: "Giffard Framboise de Ronce (raspberry liqueur)", amount: "1.5 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "singapore-sling",
    name: "Singapore Sling",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "singapore-sling-std",
      label: "Standard",
      ingredients: [
          { name: "Portobello Old Tom gin", amount: "6 cl" },
          { name: "Bénédictine D.O.M.", amount: "1.5 cl" },
          { name: "Cherry Heering cherry brandy liqueur", amount: "1.5 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "3 cl" },
          { name: "Angostura Aromatic Bitters", amount: "2 dash" },
          { name: "Orange Bitters by Angostura", amount: "2 dash" },
          { name: "Thomas Henry Soda Water", amount: "Top up with" }
      ],
      method: "Shake base ingredients with ice. Strain into glass. Top with soda.",
      glass: "Sling glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "stinger",
    name: "Stinger",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "stinger-std",
      label: "Standard",
      ingredients: [
          { name: "Rémy Martin 1738 Cognac", amount: "6 cl" },
          { name: "Giffard Menthe Pastille white crème de menthe", amount: "2.25 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Old-fashioned glass",
      garnish: "Mint sprig",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "tequila-sunrise",
    name: "Tequila Sunrise",
    image: tequila_sunriseImg,
    tier: 3,
    standardRecipe: {
      id: "tequila-sunrise-std",
      label: "Standard",
      ingredients: [
          { name: "Giffard Grenadine syrup", amount: "0.5 cl" },
          { name: "Giffard Noir de Bourgogne Cassis", amount: "0.5 cl" },
          { name: "Patrón Reposado tequila", amount: "4.5 cl" },
          { name: "Orange Curaçao liqueur", amount: "2.25 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "7.5 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "tuxedo",
    name: "Tuxedo",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "tuxedo-std",
      label: "Standard",
      ingredients: [
          { name: "Portobello Old Tom gin", amount: "4.5 cl" },
          { name: "Martini Extra Dry vermouth", amount: "4.5 cl" },
          { name: "Luxardo Maraschino liqueur", amount: "1 dash" },
          { name: "La Fée Parisienne absinthe", amount: "1 dash" },
          { name: "Orange Bitters by Angostura", amount: "2 dash" },
          { name: "Angostura Aromatic Bitters", amount: "2 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "vesper",
    name: "Vesper",
    image: vesperImg,
    tier: 3,
    standardRecipe: {
      id: "vesper-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "6 cl" },
          { name: "Ketel One Vodka", amount: "2 cl" },
          { name: "Kina aromatised wine", amount: "0.5 cl" },
          { name: "Lillet Blanc (or other aromatized wine)", amount: "0.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Martini glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "ward-eight",
    name: "Ward Eight",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "ward-eight-std",
      label: "Standard",
      ingredients: [
          { name: "Straight rye whiskey (100 proof / 50% alc./vol.)", amount: "6 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Orange juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "0.75 cl" },
          { name: "Giffard Grenadine syrup", amount: "0.5 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "whisky-mac",
    name: "Whisky Mac",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "whisky-mac-std",
      label: "Standard",
      ingredients: [
          { name: "Dewar\'s 12 Year Old Scotch whisky", amount: "4.5 cl" },
          { name: "Stone\'s Original Green Ginger Wine", amount: "3 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Old-fashioned glass",
      garnish: "Candied ginger",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "white-lady",
    name: "White Lady",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "white-lady-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "4.5 cl" },
          { name: "De Kuyper Triple Sec (40%)", amount: "2.25 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.25 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1 cl" },
          { name: "Pasteurised egg white (optional)", amount: "1.5 cl" }
      ],
      method: "Dry shake all ingredients without ice. Shake again with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "white-russian",
    name: "White Russian",
    image: white_russianImg,
    tier: 3,
    standardRecipe: {
      id: "white-russian-std",
      label: "Standard",
      ingredients: [
          { name: "Ketel One Vodka", amount: "6 cl" },
          { name: "Coffee liqueur", amount: "3 cl" },
          { name: "Single cream / half-and-half", amount: "3 cl" }
      ],
      method: "Shake all ingredients vigorously with ice. Fine strain into glass.",
      glass: "Old-fashioned glass",
      garnish: "Fresh nutmeg",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "zombie",
    name: "Zombie",
    image: zombieImg,
    tier: 3,
    standardRecipe: {
      id: "zombie-std",
      label: "Standard",
      ingredients: [
          { name: "Overproof pot still rum", amount: "3 cl" },
          { name: "Havana Club 3 Year Old rum", amount: "4.5 cl" },
          { name: "Overproof aged rum", amount: "2 cl" },
          { name: "Difford\'s Falernum liqueur", amount: "1.5 cl" },
          { name: "Pernod anise", amount: "0.125 cl" },
          { name: "Pineapple juice (fresh pressed)", amount: "3 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2 cl" },
          { name: "Grapefruit juice (pink)", amount: "1 cl" },
          { name: "Giffard Grenadine syrup", amount: "0.5 cl" }
      ],
      method: "Blend all ingredients with crushed ice until smooth. Pour into glass.",
      glass: "Collins glass",
      garnish: "Mint sprig",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "naked-and-famous",
    name: "Naked & Famous",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "naked-and-famous-std",
      label: "Standard",
      ingredients: [
          { name: "Del Maguey VIDA mezcal", amount: "2.25 cl" },
          { name: "Bittersweet orange-red aperitivo", amount: "2.25 cl" },
          { name: "Yellow Chartreuse liqueur", amount: "2.25 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.25 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "jungle-bird",
    name: "Jungle Bird",
    image: jungle_birdImg,
    tier: 4,
    standardRecipe: {
      id: "jungle-bird-std",
      label: "Standard",
      ingredients: [
          { name: "Dark/black/blackstrap rum", amount: "4.5 cl" },
          { name: "Italian red bitter liqueur", amount: "1.5 cl" },
          { name: "Pineapple juice (fresh pressed)", amount: "4.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.25 cl" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Old-fashioned glass",
      garnish: "Luxardo cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "navy-grog",
    name: "Navy Grog",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "navy-grog-std",
      label: "Standard",
      ingredients: [
          { name: "Bacardi Carta Blanca light rum", amount: "3 cl" },
          { name: "Havana Club 7yo rum", amount: "3 cl" },
          { name: "Navy rum (54.5% alc./vol.)", amount: "3 cl" },
          { name: "Pimento dram liqueur", amount: "0.75 cl" },
          { name: "Demerara / dark Muscovado sugar syrup (2 sugar to 1 water)", amount: "0.75 cl" },
          { name: "Honey syrup (3 honey to 1 water)", amount: "0.75 cl" },
          { name: "Grapefruit juice (pink)", amount: "2.25 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.25 cl" }
      ],
      method: "Muddle fruit/herbs in shaker. Add remaining ingredients. Shake with ice. Strain into glass.",
      glass: "Double old-fashioned",
      garnish: "Lime wheel",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "saturn",
    name: "Saturn",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "saturn-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "4.5 cl" },
          { name: "Difford\'s Falernum liqueur", amount: "0.75 cl" },
          { name: "Giffard Orgeat Syrup", amount: "0.75 cl" },
          { name: "Passion fruit syrup", amount: "0.75 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" }
      ],
      method: "Muddle fruit/herbs in shaker. Add remaining ingredients. Shake with ice. Strain into glass.",
      glass: "Sling glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "chartreuse-swizzle",
    name: "Chartreuse Swizzle",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "chartreuse-swizzle-std",
      label: "Standard",
      ingredients: [
          { name: "Green Chartreuse liqueur", amount: "4.5 cl" },
          { name: "Difford\'s Falernum liqueur", amount: "1.5 cl" },
          { name: "Pineapple juice (fresh pressed)", amount: "4.5 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.25 cl" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Collins glass",
      garnish: "Luxardo cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "toronto",
    name: "Toronto",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "toronto-std",
      label: "Standard",
      ingredients: [
          { name: "Canadian blended whisky", amount: "5.25 cl" },
          { name: "Fernet liqueur", amount: "0.75 cl" },
          { name: "Maple syrup", amount: "0.75 cl" },
          { name: "Angostura Aromatic Bitters", amount: "1 dash" },
          { name: "Chilled water (omit if using wet ice)", amount: "1 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "chet-baker",
    name: "Chet Baker",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "chet-baker-std",
      label: "Standard",
      ingredients: [
          { name: "Caribbean blended rum aged 6-10 years", amount: "6 cl" },
          { name: "Rosso/rouge (sweet) vermouth", amount: "1.5 cl" },
          { name: "Honey syrup (3 honey to 1 water)", amount: "1 spoon" }
      ],
      method: "Stir all ingredients over ice. Strain into glass over fresh ice.",
      glass: "Old-fashioned glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "final-ward",
    name: "Final Ward",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "final-ward-std",
      label: "Standard",
      ingredients: [
          { name: "Straight rye whiskey (100 proof / 50% alc./vol.)", amount: "2.25 cl" },
          { name: "Green Chartreuse liqueur", amount: "2.25 cl" },
          { name: "Luxardo Maraschino liqueur", amount: "2.25 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "2.25 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "southside",
    name: "Southside",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "southside-std",
      label: "Standard",
      ingredients: [
          { name: "Mint leaves", amount: "7 fresh" },
          { name: "Rutte Dry Gin", amount: "6 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2.5 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1.5 cl" }
      ],
      method: "Muddle mint and sugar gently in shaker. Add remaining ingredients. Shake with ice. Fine strain into glass.",
      glass: "Coupe glass",
      garnish: "Mint sprig",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "elderflower-collins",
    name: "Elderflower Collins",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "elderflower-collins-std",
      label: "Standard",
      ingredients: [
          { name: "Rutte Dry Gin", amount: "5 cl" },
          { name: "St-Germain elderflower liqueur", amount: "1.5 cl" },
          { name: "Luxardo Maraschino liqueur", amount: "0.5 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "3 cl" },
          { name: "Sugar syrup (65.0°brix, 2 sugar to 1 water rich syrup)", amount: "1 cl" },
          { name: "Thomas Henry Soda Water", amount: "2.5 cl" }
      ],
      method: "Shake base ingredients with ice. Strain into glass. Top with soda.",
      glass: "Collins glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "mexican-firing-squad",
    name: "Mexican Firing Squad",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "mexican-firing-squad-std",
      label: "Standard",
      ingredients: [
          { name: "Patrón Reposado tequila", amount: "6 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2 cl" },
          { name: "Giffard Grenadine syrup", amount: "1.25 cl" },
          { name: "Angostura Aromatic Bitters", amount: "2 dash" }
      ],
      method: "Build ingredients directly in glass over ice. Stir gently.",
      glass: "Highball (max 10oz/300ml)",
      garnish: "Orange twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "pornstar-martini",
    name: "Pornstar Martini",
    image: pornstar_martiniImg,
    tier: 2,
    standardRecipe: {
      id: "pornstar-martini-std",
      label: "Standard",
      ingredients: [
          { name: "Vanilla vodka", amount: "4 cl" },
          { name: "Passion fruit purée", amount: "4 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Vanilla syrup", amount: "1.5 cl" },
          { name: "Prosecco (served alongside)", amount: "6 cl" }
      ],
      method: "Shake vodka, passion fruit purée, lime juice and syrup with ice. Strain into chilled coupe glass. Serve with prosecco shot on the side.",
      glass: "Coupe glass",
      garnish: "Half passion fruit",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "porto-flip",
    name: "Porto Flip",
    image: "",
    tier: 3,
    standardRecipe: {
      id: "porto-flip-std",
      label: "Standard",
      ingredients: [
          { name: "Ruby port", amount: "4.5 cl" },
          { name: "Cognac", amount: "4.5 cl" },
          { name: "Egg yolk", amount: "1" },
          { name: "Simple syrup", amount: "0.75 cl" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Fresh nutmeg",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "angostura-colada",
    name: "Angostura Colada",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "angostura-colada-std",
      label: "Standard",
      ingredients: [
          { name: "Angostura bitters", amount: "4.5 cl" },
          { name: "Pineapple juice", amount: "3 cl" },
          { name: "Coconut cream", amount: "3 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "1.5 cl" }
      ],
      method: "Blend all ingredients with crushed ice. Pour into glass.",
      glass: "Hurricane glass",
      garnish: "Pineapple wedge & cherry",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "la-louisiana",
    name: "La Louisiana",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "la-louisiana-std",
      label: "Standard",
      ingredients: [
          { name: "Rye whiskey", amount: "3 cl" },
          { name: "Sweet vermouth", amount: "3 cl" },
          { name: "Bénédictine", amount: "1.5 cl" },
          { name: "Peychaud\'s bitters", amount: "2 dash" },
          { name: "Absinthe", amount: "2 dash" }
      ],
      method: "Stir all ingredients over ice. Strain into chilled glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "cucumber-gimlet",
    name: "Cucumber Gimlet",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "cucumber-gimlet-std",
      label: "Standard",
      ingredients: [
          { name: "Gin", amount: "6 cl" },
          { name: "Lime juice (freshly squeezed)", amount: "2 cl" },
          { name: "Simple syrup", amount: "1.5 cl" },
          { name: "Cucumber", amount: "3 slice" }
      ],
      method: "Muddle cucumber with simple syrup. Add gin and lime. Shake with ice. Fine strain into glass.",
      glass: "Coupe glass",
      garnish: "Cucumber slice",
    },
    alternativeRecipes: [],
  }
,
  {
    id: "champs-elysees",
    name: "Champs-Élysées",
    image: "",
    tier: 4,
    standardRecipe: {
      id: "champs-elysees-std",
      label: "Standard",
      ingredients: [
          { name: "Cognac", amount: "5 cl" },
          { name: "Yellow Chartreuse", amount: "1.5 cl" },
          { name: "Lemon juice (freshly squeezed)", amount: "1.5 cl" },
          { name: "Simple syrup", amount: "1 cl" },
          { name: "Angostura Aromatic Bitters", amount: "1 dash" }
      ],
      method: "Shake all ingredients with ice. Strain into chilled coupe glass.",
      glass: "Coupe glass",
      garnish: "Lemon twist",
    },
    alternativeRecipes: [],
  }

];

// Total: 100 cocktails
// Breakdown by tier: 0=4, 1=6, 2=25, 3=50, 4=15