"""
Generate apps/census/src/data/cocktails.ts from the 100-cocktail CSV.
Preserves image imports for cocktails that have existing assets.
"""

import csv
import os
import re

# Paths
CSV_PATH = os.path.join(os.path.dirname(__file__), "..", "Data", "cocktails-100.csv")
ASSETS_DIR = os.path.join(os.path.dirname(__file__), "..", "apps", "census", "src", "assets")
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "apps", "census", "src", "data", "cocktails.ts")

# IDs that should always get images if they exist — these are the 50 original IBA cocktails
EXISTING_ASSETS = set()
if os.path.isdir(ASSETS_DIR):
    for f in os.listdir(ASSETS_DIR):
        if f.endswith('.jpg'):
            # old-fashioned.jpg -> old-fashioned
            EXISTING_ASSETS.add(f.replace('.jpg', ''))


def camel_to_kebab(name: str) -> str:
    """Convert PascalCase slug to kebab-case."""
    return re.sub(r'(?<!^)(?=[A-Z])', '-', name).lower()


def sanitize_id(cocktail_id: str) -> str:
    """Sanitize ID for use as JavaScript identifier-friendly string (for the id field it's fine as-is)."""
    return cocktail_id.strip()


def escape_ts_string(s: str) -> str:
    """Escape a string for TypeScript single-quote string literal."""
    s = s.replace("\\", "\\\\")
    s = s.replace("'", "\\'")
    return s


def generate():
    # Read CSV
    rows = []
    with open(CSV_PATH, encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append(r)

    print(f"Loaded {len(rows)} cocktails from CSV")

    # Track which IDs have images
    with_images = set()
    no_images = set()

    for r in rows:
        cid = r['id']
        if cid in EXISTING_ASSETS:
            with_images.add(cid)
        else:
            no_images.add(cid)

    print(f"  With images: {len(with_images)}")
    print(f"  Without images: {len(no_images)}")

    # Build the file content
    lines = []

    # --- Header comment ---
    lines.append("// Generated by scripts/generate_cocktails_ts.py — do not edit directly")
    lines.append("// Source: Data/cocktails-100.csv")
    lines.append("")

    # --- Image imports (only for cocktails that have assets) ---
    for r in rows:
        cid = r['id']
        if cid in with_images:
            var_name = cid.replace('-', '_') + "Img"
            lines.append(f'import {var_name} from "@/assets/{cid}.jpg";')

    lines.append("")
    lines.append('import type { Cocktail } from "@/types/cocktail";')
    lines.append("")

    # --- Cocktail array ---
    lines.append("export const cocktails: Cocktail[] = [")

    for idx, r in enumerate(rows):
        cid = r['id']
        name = r['name']
        tier = r['tier']
        glass = escape_ts_string(r['glass'])
        method = escape_ts_string(r['method'])
        garnish = escape_ts_string(r['garnish'])

        # Image import variable
        if cid in with_images:
            img_var = cid.replace('-', '_') + "Img"
        else:
            img_var = '""'

        # Ingredients
        ing_count = int(r['ing_count'])
        ingredients = []
        for i in range(1, ing_count + 1):
            amount = escape_ts_string(r[f'ing_{i}_amount'])
            ing_name = escape_ts_string(r[f'ing_{i}_name'])
            ingredients.append(f'          {{ name: "{ing_name}", amount: "{amount}" }}')

        # Recipe id
        recipe_id = f"{cid}-std"

        ingredients_text = ",\n".join(ingredients)

        cocktail_entry = f"""  {{
    id: "{cid}",
    name: "{name}",
    image: {img_var},
    tier: {tier},
    standardRecipe: {{
      id: "{recipe_id}",
      label: "Standard",
      ingredients: [
{ingredients_text}
      ],
      method: "{method}",
      glass: "{glass}",
      garnish: "{garnish}",
    }},
    alternativeRecipes: [],
  }}"""

        lines.append(cocktail_entry)
        if idx < len(rows) - 1:
            lines.append(",")
        else:
            lines.append("")

    lines.append("];")
    lines.append("")
    lines.append(f"// Total: {len(rows)} cocktails")
    lines.append(f"// Breakdown by tier: 0={sum(1 for r in rows if r['tier']=='0')}, 1={sum(1 for r in rows if r['tier']=='1')}, 2={sum(1 for r in rows if r['tier']=='2')}, 3={sum(1 for r in rows if r['tier']=='3')}, 4={sum(1 for r in rows if r['tier']=='4')}")

    # Write output
    output = "\n".join(lines)

    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(output)

    print(f"\nWritten to: {OUTPUT_PATH}")
    print(f"  {len(rows)} cocktail entries, {len(with_images)} with images, {len(no_images)} without")


if __name__ == "__main__":
    generate()
